## Data Cleaning Project

Data cleaning is NOT is beyond “removing nulls” or “fixing errors blindly”, Its understanding what each column means, and deciding what to do based on the analysis goal.

My objective is to find:

❓ What is wrong in this dataset?

❓ Why is it wrong?

❓ What is the best fix?

#### 1. Importing Dependencies and Loading dataset

In [145]:
import pandas as pd
import numpy as np

In [146]:
path = "C:/Users/kolad/OneDrive/Documents/Data Science Project/Netflix_Data cleaning/netflix_titles.csv"
df=pd.read_csv(path)

In [147]:
# Preview the first 5 rows of the DataFrame
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

> The netflix data has "Nan" values in different columns

> The cast, country and listed_in columns is messy has its group of strings separated by a comma delimiter, while the date_added column has strings mixed with number "September 25, 2021".

> The duration has inconsistent mixed_type data with some showing 90mins and other showing seasons 2

#### 2. Understanding the Netflix dataset

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

There are missing values in the following columns director, cast, country, date_added, rating, duration,

In [149]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

The release_year is the only column with numerical datatype "ïnt"

#### 3. Dealing With Missing Values

In [150]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

The director, cast and country has many nulls while the date_added, rating and duration has few missing values.

Because they are vast, we can't just drop the nan rows so we will have to isolate each column to understand the reason behind the missing values.

In [151]:
# Director column- This is a categorical column, we can fill the missing values with 'Unknown' and this will not affect our analysis.

df.fillna({'director':'unknown'}, inplace = True)

In [152]:
# Cast column- This is a categorical column, we can fill the missing values with 'Unknown' and this will not affect our analysis.

df.fillna({'cast': 'unknown'}, inplace = True)

In [153]:
# Country column- We will fill the missing values with 'Unknown' and split the messy data and pick the first country in the list.
df.fillna({'country': 'unknown'}, inplace = True)

df['country'] = df['country'].str.split(',').str[0]  # split the country column by comma and take the first country in the list

In [154]:
# Date added column- We have 10 null values out of the 8007 rows, we can drop these rows without affecting our analysis.
df = df.dropna(subset=['date_added'])

In [155]:
df.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          4
duration        3
listed_in       0
description     0
dtype: int64

In [156]:

df['rating'] = df['rating'].fillna('NR')

In [157]:
# Convert the date_added column to datetime format

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [158]:
## The duration column is storing two different meanings; Movies -> minutes, TV Shows -> seasons
df['duration'].unique()

array(['90 min', '2 Seasons', '1 Season', '91 min', '125 min',
       '9 Seasons', '104 min', '127 min', '4 Seasons', '67 min', '94 min',
       '5 Seasons', '161 min', '61 min', '166 min', '147 min', '103 min',
       '97 min', '106 min', '111 min', '3 Seasons', '110 min', '105 min',
       '96 min', '124 min', '116 min', '98 min', '23 min', '115 min',
       '122 min', '99 min', '88 min', '100 min', '6 Seasons', '102 min',
       '93 min', '95 min', '85 min', '83 min', '113 min', '13 min',
       '182 min', '48 min', '145 min', '87 min', '92 min', '80 min',
       '117 min', '128 min', '119 min', '143 min', '114 min', '118 min',
       '108 min', '63 min', '121 min', '142 min', '154 min', '120 min',
       '82 min', '109 min', '101 min', '86 min', '229 min', '76 min',
       '89 min', '156 min', '112 min', '107 min', '129 min', '135 min',
       '136 min', '165 min', '150 min', '133 min', '70 min', '84 min',
       '140 min', '78 min', '7 Seasons', '64 min', '59 min', '139 min',
       '69 min', '148 min', '189 min', '141 min', '130 min', '138 min',
       '81 min', '132 min', '10 Seasons', '123 min', '65 min', '68 min',
       '66 min', '62 min', '74 min', '131 min', '39 min', '46 min',
       '38 min', '8 Seasons', '17 Seasons', '126 min', '155 min',
       '159 min', '137 min', '12 min', '273 min', '36 min', '34 min',
       '77 min', '60 min', '49 min', '58 min', '72 min', '204 min',
       '212 min', '25 min', '73 min', '29 min', '47 min', '32 min',
       '35 min', '71 min', '149 min', '33 min', '15 min', '54 min',
       '224 min', '162 min', '37 min', '75 min', '79 min', '55 min',
       '158 min', '164 min', '173 min', '181 min', '185 min', '21 min',
       '24 min', '51 min', '151 min', '42 min', '22 min', '134 min',
       '177 min', '13 Seasons', '52 min', '14 min', '53 min', '8 min',
       '57 min', '28 min', '50 min', '9 min', '26 min', '45 min',
       '171 min', '27 min', '44 min', '146 min', '20 min', '157 min',
       '17 min', '203 min', '41 min', '30 min', '194 min', '15 Seasons',
       '233 min', '237 min', '230 min', '195 min', '253 min', '152 min',
       '190 min', '160 min', '208 min', '180 min', '144 min', '5 min',
       '174 min', '170 min', '192 min', '209 min', '187 min', '172 min',
       '16 min', '186 min', '11 min', '193 min', '176 min', '56 min',
       '169 min', '40 min', '10 min', '3 min', '168 min', '312 min',
       '153 min', '214 min', '31 min', '163 min', '19 min', '12 Seasons',
       nan, '179 min', '11 Seasons', '43 min', '200 min', '196 min',
       '167 min', '178 min', '228 min', '18 min', '205 min', '201 min',
       '191 min'], dtype=object)

 We can split the duration column into two separate columns: duration_int and duration_type. The duration_int column will store the integer value of the duration (96), while the duration_type column will store the type of duration (minutes or seasons).

In [ ]:

df[['duration_int', 'duration_type']] = df['duration'].str.split(' ', expand=True)

In [162]:
# Dropping the duration nan
df = df.dropna(subset=['duration_int'])

In [163]:
df['duration_int'] = df['duration_int'].astype(int)

In [166]:
# After extracting the duration_int and duration_type columns, we can drop the original duration column as it is no longer needed.

df = df.drop(columns=['duration'])

In [167]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,duration_int,duration_type
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown,United States,2021-09-25,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",90,min
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,2021-09-24,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1,Season
3,s4,TV Show,Jailbirds New Orleans,unknown,unknown,unknown,2021-09-24,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1,Season
4,s5,TV Show,Kota Factory,unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2,Seasons

In [168]:
## Checking for duplicates
df.duplicated().sum()

np.int64(0)

#### Exporting the clean data into a dataframe

In [170]:
# Saving the cleaned DataFrame to a new CSV file
df.to_csv('C:/Users/kolad/OneDrive/Documents/Data Science Project/Netflix_Data cleaning/netflix_titles_cleaned.csv', index=False)